### ISSUE TITLE
screenshots are non visible

### ISSUE THREAD

**Issue by MaherJendoubi** [thewtex/SlicerDocker#27]
![image](https://cloud.githubusercontent.com/assets/1798510/21031465/eb68eebe-bda3-11e6-85df-43187e8ab268.png)

**Comment by thewtex** [comment]
Hmm, they work for me on Linux / Chrome and Linux / Firefox on the US East Coast.

**Comment by thewtex** [comment]
They are SVGs. @jcfr reports that he sometimes has issues with SVG badges in Firefox.  @MaherJendoubi Are you on Firefox?

**Comment by MaherJendoubi** [comment]
@thewtex I'm using Chrome and Windows 10 at Paris, France.

**Comment by jcfr** [comment]
Very strange ... are these urls working: 
* url we get when we do "copy image location": https://camo.githubusercontent.com/1674fee11f992488d6e29d7a1fc212aa56ad877b/68747470733a2f2f696d616765732e6d6963726f6261646765722e636f6d2f6261646765732f696d6167652f736c696365722f736c696365722d646570656e64656e636965732e737667
* url from the raw README.rst: https://images.microbadger.com/badges/image/slicer/slicer-base.svg

And are these properly rendered:

* ![](https://camo.githubusercontent.com/1674fee11f992488d6e29d7a1fc212aa56ad877b/68747470733a2f2f696d616765732e6d6963726f6261646765722e636f6d2f6261646765732f696d6167652f736c696365722f736c696365722d646570656e64656e636965732e737667)

* ![](https://images.microbadger.com/badges/image/slicer/slicer-base.svg)

Source is:

```
* ![](https://camo.githubusercontent.com/1674fee11f992488d6e29d7a1fc212aa56ad877b/68747470733a2f2f696d616765732e6d6963726f6261646765722e636f6d2f6261646765732f696d6167652f736c696365722f736c696365722d646570656e64656e636965732e737667)

* ![](https://images.microbadger.com/badges/image/slicer/slicer-base.svg)
```


Otherwise the regular url is

**Comment by MaherJendoubi** [comment]
@jcfr @thewtex I really apologize because it's a networking problem.

**Comment by jcfr** [comment]
No problem :smile: 

Let us know how things works out for you and the kind of cool project you are working one :+1:

**Comment by MaherJendoubi** [comment]
@jcfr I'm trying to port CT Scans to 3D Holograms for the Microsoft Hololens. The problem is that the Hololens work with unity3D and not 3D Slicer...

**Comment by MaherJendoubi** [comment]
@jcfr https://developer.microsoft.com/en-us/windows/holographic/install_the_tools

**Comment by MaherJendoubi** [comment]
@jcfr The Unity engine is an easy way to get started building a holographic app.
